
import javax.swing.JOptionPane;

public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */

    int turn = 2;
    int buttonused[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
    int pXwon[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
    int pOwon[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };

    int pXwon() {
        if (pXwon[0] == 1 && pXwon[1] == 1 && pXwon[2] == 1) {
            return 1;
        }
        if (pXwon[3] == 1 && pXwon[4] == 1 && pXwon[5] == 1) {
            return 1;
        }
        if (pXwon[6] == 1 && pXwon[7] == 1 && pXwon[8] == 1) {
            return 1;
        }
        if (pXwon[0] == 1 && pXwon[3] == 1 && pXwon[6] == 1) {
            return 1;
        }
        if (pXwon[1] == 1 && pXwon[4] == 1 && pXwon[7] == 1) {
            return 1;
        }
        if (pXwon[2] == 1 && pXwon[5] == 1 && pXwon[8] == 1) {
            return 1;
        }
        if (pXwon[2] == 1 && pXwon[4] == 1 && pXwon[6] == 1) {
            return 1;
        }
        if (pXwon[0] == 1 && pXwon[4] == 1 && pXwon[8] == 1) {
            return 1;
        }
        return 0;
    }

    int pOwon() {
        if (pOwon[0] == 1 && pOwon[1] == 1 && pOwon[2] == 1) {
            return 1;
        }
        if (pOwon[3] == 1 && pOwon[4] == 1 && pOwon[5] == 1) {
            return 1;
        }
        if (pOwon[6] == 1 && pOwon[7] == 1 && pOwon[8] == 1) {
            return 1;
        }
        if (pOwon[0] == 1 && pOwon[3] == 1 && pOwon[6] == 1) {
            return 1;
        }
        if (pOwon[1] == 1 && pOwon[4] == 1 && pOwon[7] == 1) {
            return 1;
        }
        if (pOwon[2] == 1 && pOwon[5] == 1 && pOwon[8] == 1) {
            return 1;
        }
        if (pOwon[2] == 1 && pOwon[4] == 1 && pOwon[6] == 1) {
            return 1;
        }
        if (pOwon[0] == 1 && pOwon[4] == 1 && pOwon[8] == 1) {
            return 1;
        }
        return 0;
    }

    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b2 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b0 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        b2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        b2.setForeground(new java.awt.Color(0, 153, 51));
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        b1.setForeground(new java.awt.Color(0, 153, 51));
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b0.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        b0.setForeground(new java.awt.Color(0, 153, 51));
        b0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b0ActionPerformed(evt);
            }
        });

        b7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        b7.setForeground(new java.awt.Color(0, 153, 51));
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });

        b8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        b8.setForeground(new java.awt.Color(0, 153, 51));
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });

        b6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        b6.setForeground(new java.awt.Color(0, 153, 51));
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        b5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        b5.setForeground(new java.awt.Color(0, 153, 51));
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        b3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        b3.setForeground(new java.awt.Color(0, 153, 51));
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        b4.setForeground(new java.awt.Color(0, 153, 51));
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 204));
        jButton1.setText("REFRESH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setText("TIC TAC TOE ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(48, 48, 48)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(b0,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 108,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(b1,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 108,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(b2,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 108,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(b3,
                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                108,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(b6,
                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                108,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                layout.createSequentialGroup()
                                                                                        .addComponent(b4,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                108,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addGap(18, 18, 18)
                                                                                        .addComponent(b5,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                108,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                layout.createSequentialGroup()
                                                                                        .addComponent(b7,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                108,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addGap(18, 18, 18)
                                                                                        .addComponent(b8,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                108,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(132, 132, 132)
                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 191,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(53, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(105, 105, 105)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 108,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 108,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(b0, javax.swing.GroupLayout.PREFERRED_SIZE, 108,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 108,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 108,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 108,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 108,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 108,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 108,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b0ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_b0ActionPerformed
        if (buttonused[0] == 0) {
            if (turn % 2 == 0) {
                turn++;
                b0.setText("X");
                buttonused[0] = 1;
                pXwon[0] = 1;

                int result1 = pXwon();
                int result2 = pOwon();

                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player X won!!!");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player O won!!!");
                }
            } else {
                turn++;
                b0.setText("0");
                buttonused[0] = 1;
                pOwon[0] = 1;
                int result1 = pXwon();
                int result2 = pOwon();

                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player X won!!!");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player O won!!!");
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "This Button is Used!!!");
        }
    }// GEN-LAST:event_b0ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_b1ActionPerformed
        if (buttonused[1] == 0) {
            if (turn % 2 == 0) {
                turn++;
                b1.setText("X");
                buttonused[1] = 1;
                pXwon[1] = 1;

                int result1 = pXwon();
                int result2 = pOwon();

                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player X won!!!");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player O won!!!");
                }
            } else {
                turn++;
                b1.setText("0");
                buttonused[1] = 1;
                pOwon[1] = 1;
                int result1 = pXwon();
                int result2 = pOwon();

                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player X won!!!");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player O won!!!");
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "This Button is Used!!!");
        }
    }// GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_b2ActionPerformed
        if (buttonused[2] == 0) {
            if (turn % 2 == 0) {
                turn++;
                b2.setText("X");
                buttonused[2] = 1;
                pXwon[2] = 1;

                int result1 = pXwon();
                int result2 = pOwon();

                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player X won!!!");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player O won!!!");
                }
            } else {
                turn++;
                b2.setText("0");
                buttonused[2] = 1;
                pOwon[2] = 1;
                int result1 = pXwon();
                int result2 = pOwon();

                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player X won!!!");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player O won!!!");
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "This Button is Used!!!");
        }
    }// GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_b3ActionPerformed
        if (buttonused[3] == 0) {
            if (turn % 2 == 0) {
                turn++;
                b3.setText("X");
                buttonused[3] = 1;
                pXwon[3] = 1;

                int result1 = pXwon();
                int result2 = pOwon();

                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player X won!!!");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player O won!!!");
                }
            } else {
                turn++;
                b3.setText("0");
                buttonused[3] = 1;
                pOwon[3] = 1;
                int result1 = pXwon();
                int result2 = pOwon();

                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player X won!!!");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player O won!!!");
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "This Button is Used!!!");
        }
    }// GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_b4ActionPerformed
        if (buttonused[4] == 0) {
            if (turn % 2 == 0) {
                turn++;
                b4.setText("X");
                buttonused[4] = 1;
                pXwon[4] = 1;

                int result1 = pXwon();
                int result2 = pOwon();

                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player X won!!!");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player O won!!!");
                }
            } else {
                turn++;
                b4.setText("0");
                buttonused[4] = 1;
                pOwon[4] = 1;
                int result1 = pXwon();
                int result2 = pOwon();

                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player X won!!!");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player O won!!!");
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "This Button is Used!!!");
        }
    }// GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_b5ActionPerformed
        if (buttonused[5] == 0) {
            if (turn % 2 == 0) {
                turn++;
                b5.setText("X");
                buttonused[5] = 1;
                pXwon[5] = 1;

                int result1 = pXwon();
                int result2 = pOwon();

                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player X won!!!");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player O won!!!");
                }
            } else {
                turn++;
                b5.setText("0");
                buttonused[5] = 1;
                pOwon[5] = 1;
                int result1 = pXwon();
                int result2 = pOwon();

                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player X won!!!");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player O won!!!");
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "This Button is Used!!!");
        }
    }// GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_b6ActionPerformed
        if (buttonused[6] == 0) {
            if (turn % 2 == 0) {
                turn++;
                b6.setText("X");
                buttonused[6] = 1;
                pXwon[6] = 1;

                int result1 = pXwon();
                int result2 = pOwon();

                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player X won!!!");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player O won!!!");
                }
            } else {
                turn++;
                b6.setText("0");
                buttonused[6] = 1;
                pOwon[6] = 1;
                int result1 = pXwon();
                int result2 = pOwon();

                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player X won!!!");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player O won!!!");
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "This Button is Used!!!");
        }
    }// GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_b7ActionPerformed
        if (buttonused[7] == 0) {
            if (turn % 2 == 0) {
                turn++;
                b7.setText("X");
                buttonused[7] = 1;
                pXwon[7] = 1;

                int result1 = pXwon();
                int result2 = pOwon();

                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player X won!!!");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player O won!!!");
                }
            } else {
                turn++;
                b7.setText("0");
                buttonused[7] = 1;
                pOwon[7] = 1;
                int result1 = pXwon();
                int result2 = pOwon();

                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player X won!!!");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player O won!!!");
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "This Button is Used!!!");
        }
    }// GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_b8ActionPerformed
        if (buttonused[8] == 0) {
            if (turn % 2 == 0) {
                turn++;
                b8.setText("X");
                buttonused[8] = 1;
                pXwon[8] = 1;

                int result1 = pXwon();
                int result2 = pOwon();

                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player X won!!!");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player O won!!!");
                }
            } else {
                turn++;
                b8.setText("0");
                buttonused[8] = 1;
                pOwon[8] = 1;
                int result1 = pXwon();
                int result2 = pOwon();

                if (result1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player X won!!!");
                } else if (result2 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Player O won!!!");
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "This Button is Used!!!");
        }
    }// GEN-LAST:event_b8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        b0.setText("");
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");

        turn = 2;
        for (int i = 0; i < 9; i++) {
            buttonused[i] = 0;
        }
        for (int i = 0; i < 9; i++) {
            pXwon[i] = 0;
        }
        for (int i = 0; i < 9; i++) {
            pOwon[i] = 0;
        }

    }// GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
